### PR TITLE
6 view list of comments on each article

### PR DESCRIPTION
**Pull request by edeharrison**

### CODE REVIEW

**Review by HannahBurks — CHANGES_REQUESTED** [review]
Very nice Ede! Just a couple of tweaks 
- Comment card is an empty file -  remove this for now 
-  Add a message if there are no comments on a review yet 

Once added, please send another PR 😄

**Comment by edeharrison** [comment]
> * Comment card is an empty file -  remove this for now

Done :)

> * Add a message if there are no comments on a review yet

I've added a "No comments" but it's not very nice. I had some trouble with the jsx syntax (when and how to utilise ternaries / when to pick the return, and so on. I'll try and make an improvement to it later.

`Comments.jsx`
Screenshot 2023-03-15 at 08 27 10

**Review by HannahBurks — APPROVED** [review]
Excellent Ede - feel free to merge 😄

**Comment by edeharrison** [comment]
> Excellent Ede - feel free to merge 😄

Thanks Hannah :)

**Pull request merged**
